version: '3'

services:
  mock_qdoc:
    image: mock_qdoc:latest
    build:
      context: ./mock_server
    environment:
      - "MOCK_SERVER_PORT=4567"
      - "FIREBASE_AUTH_EMULATOR_HOST=firebase:9099"
      - "PROJECT_ID=qdoc-309515"
    volumes:
      - "./mock_server:/src"
    ports:
      - "4567:4567"

  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - "./firebase:/home/node"
    ports:
      - "9099:9099"
      - "4579:4579"
    command: [ "firebase", "emulators:start" ]